language: scala
scala: 2.11.8
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8

script:
 - sbt -jvm-opts travis/jvmopts.compile compile
 - sbt -jvm-opts travis/jvmopts.test test
 - sbt -jvm-opts travis/jvmopts.test scalastyle
