language: scala
scala: 2.11.8
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8
sudo: required
services:
 - docker

script:
 - sbt -jvm-opts travis/jvmopts.compile compile
 - sbt -jvm-opts travis/jvmopts.test test
 - sbt -jvm-opts travis/jvmopts.test scalastyle
 - sbt -jvm-opts travis/jvmopts.assembly assembly
 - docker build -t cdrgenerator .

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/repository


after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - test $TRAVIS_BRANCH = "master" && ./trigger_core_repo_build.sh
